### ISSUE TITLE
"InsecurePlatformWarning" on every search

### ISSUE THREAD

**Issue by fitzgen** [Osmose/dxr-cmd#4]
```
InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
```

Any ideas?

**Comment by Osmose** [comment]
The linked URL says either upgrade to Python 2.7.9 or higher, or we include PyOpenSSL (and some friends because we're using requests/urllib3) in the dependencies. I guess the latter is better as it doesn't rely on users of the command to be on a certain Python version.

**Comment by Osmose** [comment]
PyOpenSSL included, I was able to replicate and fix the issue locally and pushed an update to PyPI.

Thanks for the report!

**Comment by fitzgen** [comment]
When I try to update to get this change, I am getting package requirement conflicts: https://gist.github.com/fitzgen/d8d28a6eeb2dea0198e7

Is this an issue with my python setup or related to the dependencies required here?

**Comment by fitzgen** [comment]
Also, thanks for being so responsive!

**Comment by Osmose** [comment]
> Is this an issue with my python setup or related to the dependencies required here?

I suspect it's your setup but I'm not 100% sure. That log shows that it's installing six 1.9.0, so the version conflict should be invalid.

Does it happen if you try to update again? If you run `pip freeze`, what output do you get?

**Comment by fitzgen** [comment]
If I uninstall six and re-run the upgrade command it works. _shrug_
